---
galaxy_info:
  author: your name
  description: your description
  company: your company
  license: license (GPLv2, MIT, etc)
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []

dependencies: []
